"""empty message

Revision ID: 39629fda4ac7
Revises: 218b45050ca3
Create Date: 2023-03-24 19:07:30.036135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39629fda4ac7'
down_revision = '218b45050ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_token_id_fkey', type_='foreignkey')
        batch_op.drop_column('token_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_token_id_fkey', 'verification_tokens', ['token_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
