"""empty message

Revision ID: 70fa6841aac3
Revises: e2d68a97b615
Create Date: 2023-03-25 12:14:21.215770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fa6841aac3'
down_revision = 'e2d68a97b615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_deliverable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=3000), nullable=True))
        batch_op.drop_column('category')

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('is_deliverable')
        batch_op.drop_column('price')
        batch_op.drop_column('is_available')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=3000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_deliverable', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar')
        batch_op.drop_column('rating')
        batch_op.drop_column('is_deliverable')
        batch_op.drop_column('is_available')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
